FROM workflow-base:latest

WORKDIR /app

COPY streamlit_app ./streamlit_app
COPY app ./app

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
